[2025-03-27T12:16:56.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T12:16:56.054+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.add_launches_to_table manual__2025-03-27T12:16:34.835906+00:00 [queued]>
[2025-03-27T12:16:56.062+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.add_launches_to_table manual__2025-03-27T12:16:34.835906+00:00 [queued]>
[2025-03-27T12:16:56.062+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T12:16:56.075+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): add_launches_to_table> on 2025-03-27 12:16:34.835906+00:00
[2025-03-27T12:16:56.082+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=508) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T12:16:56.083+0000] {standard_task_runner.py:72} INFO - Started process 510 to run task
[2025-03-27T12:16:56.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'add_launches_to_table', 'manual__2025-03-27T12:16:34.835906+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmplzqy5gmm']
[2025-03-27T12:16:56.085+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask add_launches_to_table
[2025-03-27T12:16:56.326+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.add_launches_to_table manual__2025-03-27T12:16:34.835906+00:00 [running]> on host 2753c0b03e32
[2025-03-27T12:16:56.399+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='add_launches_to_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T12:16:34.835906+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T12:16:34.835906+00:00'
[2025-03-27T12:16:56.400+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T12:16:56.400+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T12:16:56.401+0000] {logging_mixin.py:190} INFO - Current task name:add_launches_to_table state:running start_date:2025-03-27 12:16:56.054801+00:00
[2025-03-27T12:16:56.401+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-03-27T12:16:56.401+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T12:16:56.409+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2025-03-27T12:16:58.458+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T12:16:58.468+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T12:16:58.469+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=add_launches_to_table, run_id=manual__2025-03-27T12:16:34.835906+00:00, execution_date=20250327T121634, start_date=20250327T121656, end_date=20250327T121658
[2025-03-27T12:16:58.492+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-27T12:16:58.492+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-27T12:16:58.493+0000] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-03-27 12:16:34.844169+00:00
[2025-03-27T12:16:58.493+0000] {logging_mixin.py:190} INFO - Task hostname:2753c0b03e32 operator:PythonOperator
[2025-03-27T12:16:58.520+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T12:16:58.720+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-27T12:16:58.722+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
